.TH NAME 1
.SH NAME
ticker \- scroll messages across the screen
.SH SYNOPSIS
.B ticker
.I "[options] [message]"
.SH "DESCRIPTION"
.BR ticker
is a program that continually scrolls a given message across the screen.
There is also an interface to allow other programs to change the message.
.SH KEYS
.TP
.B +, [up arrow]
Increase scroll speed.
.TP
.B -, [down arrw]
Decrease scroll speed.
.TP
.B [space]
Pause. Press any key to unpause.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-u, \-\-upper
Scroll text on the top line of the screen. (Default)
.TP
.B \-l, \-\-lower
Scroll text on the bottom line of the screen.
.TP
.B \-fcolor, \-\-foreground=color
Use the specified color as the forground color of the text that is scrolled.
The colors that may be used are:
.RS
 black           gray
 red             brightred
 green           brightgreen
 brown           yellow
 blue            brightblue
 magenta         brightmagenta
 cyan            brightcyan
 lightgray       white
.RE
.TP
.B \-bcolor, \-\-background=color
Use the specified color as the background color of the text that is
scrolled. On most terminals, the background color can only be one of the colors
listed in the first column above.
.TP
.B \-dsecs, \-\-delay=secs
Number of seconds delay between updates of the display. This controls how
fast the text scrolls. You may use decimals to specify faster scroll speeds.
The default delay is 1 second; I find 0.1 more pleasing.
.TP
.B \-snum, \-\-sysv=num
Read messages to display from the sysv shared memory segment with an id of
num. This is only for use by other programs that need to be able to change
the text
.BR ticker
displays.
.TP
.B \-Snum, \-\-size=num
Size of the shared memory segment to read, when using shared memory
communication with another program. Default is 80 characters.
.TP
.B \-csecs, \-\-check=secs
Minimum time between checks of the shared memory segment for a new message.
Default is every second. It may in fact check considerably less often, as it
only checks for a new message once per time that the current message scrolls
around the screen.
.TP
.B message
The message to scroll. Required unless -s is used, in which case it is
optional.
.SH NOTES
To use the other 23 or so lines of your screen for something useful while
the ticker is running, you might want to use
.BR splitvt (1)
.SH AUTHOR
Joey Hess <joey@kitenet.net>
