---
- name: Update the APT repository
  apt: update_cache=yes
  sudo: True
  tags:
    - needs_internet_connection

- name: Upgrade the packages
  apt: upgrade=full
  sudo: True
  tags:
    - needs_internet_connection
