#!/usr/bin/env bash
echo "bashbot: a simple bot written almost entirely in bash.  you can find the source at https://github.com/joshcartwright/bashbot"

[ -d .git ] && {
   echo -n "... working directory currently at commit ";
   git rev-parse HEAD
}
